[background]
foreground = "#222222"

[left_index]
foreground = "#ffcc66"
bold = true

[left_word]
foreground = "#cbcbcb"

[right_index]
foreground = "#f2777a"
bold = true

[right_word]
foreground = "#cbcbcb"

[left_header]
foreground = "#ffcc66"
bold = true

[right_header]
foreground = "#f2777a"
bold = true
